monolog:
    channels: ['cmd']
    handlers:
        app:
            # log messages (since debug is the lowest level)
            level:    debug
            type: rotating_file
            max_files: 10
            path:     '%kernel.logs_dir%/app.log'
            channels: [app]
            formatter: monolog.my_line_formatter

        cmd:
            #log messages from commands
            level: debug #info
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/cmd.log'
            channels: [cmd]
            formatter: monolog.my_line_formatter

        doctrine:
            # log messages (since debug is the lowest level)
            level:    debug #warning
            type: rotating_file
            max_files: 10
            path:     '%kernel.logs_dir%/doctrine.log'
            channels: [doctrine]
            formatter: monolog.my_line_formatter

        security:
            # log messages (since debug is the lowest level)
            level:    debug #warning
            type: rotating_file
            max_files: 10
            path:     '%kernel.logs_dir%/security.log'
            channels: [security]
            formatter: monolog.my_line_formatter

        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            channels: ["!app", "!cmd"]
        nested:
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            formatter: monolog.my_line_formatter

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
